import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevResourceHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.variable} font-sans antialiased`}>
        <div className="min-h-screen bg-blue-50">
          <header className="bg-blue-900 text-white p-6">
            <h1 className="text-2xl font-bold font-sans">DevResourceHub</h1>
          </header>
          <main className="container mx-auto p-4">{children}</main>
        </div>
        <footer className="bg-blue-900 text-white py-8 mt-20">
          <div className="max-w-6xl mx-auto px-4 text-center">
            <p className="mb-4">© 2024 DevResourceHub. All rights reserved.</p>
            <div className="flex justify-center space-x-6">
              <a href="#" className="hover:text-blue-200 transition-colors">
                Terms
              </a>
              <a href="#" className="hover:text-blue-200 transition-colors">
                Privacy
              </a>
              <a href="#" className="hover:text-blue-200 transition-colors">
                Contact
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
